# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/control_employees.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Control(object):
    def setupUi(self, Control):
        Control.setObjectName("Control")
        Control.resize(939, 626)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../staff_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Control.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Control)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Control)
        self.tabWidget.setObjectName("tabWidget")
        self.workersTab = QtWidgets.QWidget()
        self.workersTab.setObjectName("workersTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.workersTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newWorkerBtn = QtWidgets.QPushButton(self.workersTab)
        self.newWorkerBtn.setObjectName("newWorkerBtn")
        self.horizontalLayout.addWidget(self.newWorkerBtn)
        self.setWorkerBtn = QtWidgets.QPushButton(self.workersTab)
        self.setWorkerBtn.setObjectName("setWorkerBtn")
        self.horizontalLayout.addWidget(self.setWorkerBtn)
        self.deleteWorkerBtn = QtWidgets.QPushButton(self.workersTab)
        self.deleteWorkerBtn.setObjectName("deleteWorkerBtn")
        self.horizontalLayout.addWidget(self.deleteWorkerBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.outputWorkers = QtWidgets.QTableWidget(self.workersTab)
        self.outputWorkers.setObjectName("outputWorkers")
        self.outputWorkers.setColumnCount(0)
        self.outputWorkers.setRowCount(0)
        self.verticalLayout.addWidget(self.outputWorkers)
        self.tabWidget.addTab(self.workersTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(Control)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Control)

    def retranslateUi(self, Control):
        _translate = QtCore.QCoreApplication.translate
        Control.setWindowTitle(_translate("Control", "Управление"))
        self.newWorkerBtn.setText(_translate("Control", "Добавить нового сотрудника"))
        self.setWorkerBtn.setText(_translate("Control", "Изменить данные сотрудника"))
        self.deleteWorkerBtn.setText(_translate("Control", "Удалить данные сотрудника"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.workersTab), _translate("Control", "Сотрудники"))
